<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Aborting" Id="{53b868d1-8bc9-4c10-8ac2-c1d64eeae366}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Aborting
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="CyclicLogic" Id="{6c0f6590-0459-482e-8713-8ce383ea8165}">
      <Declaration><![CDATA[METHOD CyclicLogic : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="Aborting">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Aborting.CyclicLogic">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>