<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Clearing" Id="{a6f0b167-4c13-4b94-937d-2718ad9d0c4c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Clearing IMPLEMENTS ITF_PackMLState, ITF_States
VAR
	_MyContext : REFERENCE TO SomeMachine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="AbortingState" Id="{289d3ffc-7b4a-43d3-ba94-00b81ee45b46}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY AbortingState : ITF_PackMLState
]]></Declaration>
      <Get Name="Get" Id="{f6503087-aad9-4857-9bca-b2ab43a66291}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{b4775905-1428-4dda-86e8-793e0a2401c5}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="CyclicLogic" Id="{a9ea858b-2722-4d90-afa7-e9b930e801d5}">
      <Declaration><![CDATA[METHOD CyclicLogic : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="EStop" Id="{549d8647-c1b6-4564-b600-4c8d59c32a93}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD EStop : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="MyNextState" Id="{c5e8b3b8-c273-49c4-b3b5-da399219fc7a}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY MyNextState : ITF_PackMLState
]]></Declaration>
      <Get Name="Get" Id="{935bf004-80a0-47f1-8287-b9c9ef0d85cc}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{856f37d3-8bc5-4951-9fa0-03b4ba94d440}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="Reset" Id="{e79bc8a8-656b-4d44-a6fa-8bfcb2bf92df}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Reset : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetContext" Id="{94d8d472-e609-456d-a377-2295695183ba}">
      <Declaration><![CDATA[METHOD SetContext : BOOL
VAR_INPUT
	context	: REFERENCE TO SomeMachine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_MyContext REF= context;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Start" Id="{d70cc64b-471d-4407-83ae-9ec920ed16af}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Start : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stop" Id="{020009b6-cd1f-4ff7-99d7-2fbd1f97d684}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Stop : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="StoppingState" Id="{5f00ea3b-5fb6-4d7a-930a-9a480fe69027}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY StoppingState : ITF_PackMLState
]]></Declaration>
      <Get Name="Get" Id="{c0e8bd63-5af1-434b-a0e7-fdfef9ae4c81}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{99057099-4d5c-40e4-a595-e3cf666d36ba}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <LineIds Name="Clearing">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Clearing.AbortingState.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Clearing.AbortingState.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Clearing.CyclicLogic">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="Clearing.EStop">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Clearing.MyNextState.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Clearing.MyNextState.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Clearing.Reset">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Clearing.SetContext">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="Clearing.Start">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Clearing.Stop">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Clearing.StoppingState.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Clearing.StoppingState.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>