<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Stopping" Id="{9157fb53-3b36-484b-96f5-31503e53a781}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Stopping IMPLEMENTS ITF_PackMLState
VAR
	_MyContext : REFERENCE TO SomeMachine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="CyclicLogic" Id="{b1c4d5e0-f2e7-46dc-be85-09efde05b463}">
      <Declaration><![CDATA[METHOD CyclicLogic : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="EStop" Id="{46f7e2a4-ecb5-4195-a804-c9cbc0ab0701}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD EStop : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Reset" Id="{d53d2e7b-fd5f-4594-bc83-6f2da0e134a4}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Reset : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetContext" Id="{28aab228-961a-4647-b5fd-003e6e7ddab1}">
      <Declaration><![CDATA[METHOD SetContext : BOOL
VAR_INPUT
	context	: REFERENCE TO SomeMachine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_MyContext REF= context;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Start" Id="{1f2401c8-e5f5-4847-8e73-edd8f35c4748}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Start : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stop" Id="{a881fa75-46f2-4c5d-8fcc-f63f6f6316fc}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Stop : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="Stopping">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.CyclicLogic">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.EStop">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.Reset">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.SetContext">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.Start">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.Stop">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>