<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Stopping" Id="{9157fb53-3b36-484b-96f5-31503e53a781}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Stopping IMPLEMENTS ITF_PackMLState, ITF_States
VAR
	_MyContext : ITF_PackMLMachine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="AbortingState" Id="{12d746e4-45d6-4347-abbc-97b2f11ef8e1}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY AbortingState : ITF_PackMLState
]]></Declaration>
      <Get Name="Get" Id="{fc603993-f816-4c6c-a292-bab77e7b8fe8}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{69a1bd5b-e714-4358-bf87-2f229aad4e78}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="CyclicLogic" Id="{b1c4d5e0-f2e7-46dc-be85-09efde05b463}">
      <Declaration><![CDATA[METHOD CyclicLogic : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_MyContext.ChangeState(MyNextState);]]></ST>
      </Implementation>
    </Method>
    <Method Name="EStop" Id="{46f7e2a4-ecb5-4195-a804-c9cbc0ab0701}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD EStop : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="MyNextState" Id="{9768a1f5-5bf5-4cff-b05d-99fbd0d83749}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY MyNextState : ITF_PackMLState
]]></Declaration>
      <Get Name="Get" Id="{99c8e107-6915-4275-9d16-daefba6eaa64}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{8c03aabf-ccbe-417e-b028-853379fea61c}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="Reset" Id="{d53d2e7b-fd5f-4594-bc83-6f2da0e134a4}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Reset : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetContext" Id="{28aab228-961a-4647-b5fd-003e6e7ddab1}">
      <Declaration><![CDATA[METHOD SetContext : BOOL
VAR_INPUT
	context	: ITF_PackMLMachine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_MyContext := context;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Start" Id="{1f2401c8-e5f5-4847-8e73-edd8f35c4748}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Start : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stop" Id="{a881fa75-46f2-4c5d-8fcc-f63f6f6316fc}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Stop : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="StoppingState" Id="{877c1349-a1a5-467c-b869-bad9fd0119f9}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY StoppingState : ITF_PackMLState
]]></Declaration>
      <Get Name="Get" Id="{4dc82fe0-e431-4ed0-9192-550390830ab0}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{a450c690-b693-4bff-bcff-127f81d1aa7a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <LineIds Name="Stopping">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.AbortingState.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.AbortingState.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.CyclicLogic">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.EStop">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.MyNextState.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.MyNextState.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.Reset">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.SetContext">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.Start">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.Stop">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.StoppingState.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Stopping.StoppingState.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>