<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="MAIN" Id="{020d1cff-9f22-4cff-8b05-a70d8068ca5d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	CalcTestSuite : MyCalculatorTestSuite;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[CalcTestSuite();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>