<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="adsCommunication" Id="{2e5f369c-00b9-4463-852a-b63ad1f6bae6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK adsCommunication IMPLEMENTS ITF_ReportDataTool
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Report" Id="{8b03de4e-b985-45c4-b193-670cfc500963}">
      <Declaration><![CDATA[METHOD Report : BOOL
VAR_INPUT
	somemessage : ARRAY[0..5] OF BYTE;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="adsCommunication">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="adsCommunication.Report">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>