<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MyControlClass" Id="{22f84247-0a53-41b5-853f-1172464fa996}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MyControlClass
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MyControlClass">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>