<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{8df75bd0-3f8f-4732-b781-bc9d1ba921fd}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	dataService : ADSDataService;
	myMachine : MachineControl := (DataService := dataService);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>