<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EtherCATDevice" Id="{af8f1906-b637-4799-829a-dc8018136702}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK EtherCATDevice IMPLEMENTS I_EtherCATDevice
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="IsDeviceOK" Id="{bfa56fa0-7124-4f0f-b373-cf9908c856da}">
      <Declaration><![CDATA[METHOD IsDeviceOK : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IsDeviceOK := true;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="EtherCATDevice">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="EtherCATDevice.IsDeviceOK">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>