<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="SomeMachine" Id="{ff6886fb-65b8-468b-be70-46b545e120bf}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SomeMachine
VAR
	_MyState : ITF_PackMLState;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="CyclicLogic" Id="{cf8cfe0e-a409-463c-bd73-24a121647ac1}">
      <Declaration><![CDATA[METHOD CyclicLogic : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF _MyState <> 0 THEN
	_MyState.CyclicLogic();
END_IF]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="SomeMachine">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="SomeMachine.CyclicLogic">
      <LineId Id="5" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>