<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{3c71bcc5-3027-453b-a942-efad1d7940d1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	MyAnalogueTerminal : AnalogueTerminal;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>