<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EtherCATFactory" Id="{068d6bf7-c72d-464f-947f-295d84e58383}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EtherCATFactory
VAR
	DynamicMemoryManager : FB_DynMem_Manager2;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EtherCATFactory">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>