<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="LimitDecorator" Id="{9de537f0-d915-4a60-874f-abd46092d676}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK LimitDecorator IMPLEMENTS ITF_Analogue
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="LimitDecorator">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>