<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="SortYourNumbers" Id="{1cb95dd3-9e23-406c-9f42-1c70d1bd3662}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM SortYourNumbers
VAR
	TestArray : ARRAY[0..9] OF INT := [1,3,8,5,2,9,4,7,6,10];
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="SortYourNumbers">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>