<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{cfeb14e3-e49d-4d05-801a-00ad13175c31}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	MachineControl : ControlPanel;
	MachineLamps : LampControl := (Controller := MachineControl);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[MachineLamps.Cycle();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>