<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="BasicObject" Id="{2033108e-e225-43e0-87bf-73fc6ab5005b}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK BasicObject IMPLEMENTS ITF_Cyclic
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Cycle" Id="{334a731c-ef71-4cbf-9036-d17ecc862968}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Cycle : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="BasicObject">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="BasicObject.Cycle">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>