<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Mover" Id="{5bd059eb-f1f0-4601-a642-acba93ef29cd}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK Mover IMPLEMENTS ITF_Cyclic, ITF_Mover
VAR
	myMaxVelo : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Cycle" Id="{7f2a9182-cb07-43c8-be8a-bfdb4121e6df}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Cycle : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Velocity" Id="{0815c89a-30e6-4473-a172-d2cdba7ed99a}">
      <Declaration><![CDATA[PROPERTY Velocity : LREAL]]></Declaration>
      <Get Name="Get" Id="{eaa753c1-2f95-44fd-9d79-dc090c36f2c7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Velocity := myMaxVelo;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{e3233391-a918-4bc8-a737-e80c5f7da7d3}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[myMaxVelo := Velocity;]]></ST>
        </Implementation>
      </Set>
    </Property>
    <LineIds Name="Mover">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Mover.Cycle">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Mover.Velocity.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Mover.Velocity.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>