<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Part" Id="{c6022a1a-ace8-47d1-b56d-00a06f3159aa}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Part EXTENDS ITF_Cyclic
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Part">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>