<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Station" Id="{3a164f31-1435-4c24-a4b9-f33358c56274}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK Station IMPLEMENTS ITF_Cyclic, ITF_Station
VAR
	MyTrackPosition : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Cycle" Id="{4d5d8ab9-24a7-46b5-9b8b-8d304d0099b1}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Cycle : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Position" Id="{fb36e890-449c-4d47-b4cb-eb49a6408d7a}">
      <Declaration><![CDATA[PROPERTY Position : LREAL]]></Declaration>
      <Get Name="Get" Id="{0df87081-8cf8-43c3-9327-5e9d6dbdd976}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Position := MyTrackPosition;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{bac9dc6f-2656-4cd4-aa2c-503f999d8434}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[MyTrackPosition := Position;]]></ST>
        </Implementation>
      </Set>
    </Property>
    <LineIds Name="Station">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Station.Cycle">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Station.Position.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Station.Position.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>