<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Track" Id="{85367b14-735c-4b56-a6a4-1e4f0d6b84de}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Track EXTENDS ITF_Cyclic
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Track">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>