<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Track" Id="{85367b14-735c-4b56-a6a4-1e4f0d6b84de}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK Track IMPLEMENTS ITF_Cyclic, ITF_Track
VAR
	MyTrackLength : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Cycle" Id="{143b5232-be14-4dd2-a974-cabdb0e0e60e}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Cycle : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Length" Id="{4a8205ad-4c25-4843-adb0-8b1b2dc7e73d}">
      <Declaration><![CDATA[PROPERTY Length : LREAL]]></Declaration>
      <Get Name="Get" Id="{064eca0f-bf2e-47ee-ad00-7c5bb401c560}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Length := MyTrackLength;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{93dcff8d-af9f-4da1-91ad-0a9b1b507a0c}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[MyTrackLength := Length;]]></ST>
        </Implementation>
      </Set>
    </Property>
    <LineIds Name="Track">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Track.Cycle">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Track.Length.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Track.Length.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>