<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="XtsCAGroup" Id="{7117239f-c04d-4613-b1bc-99efd400e059}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK XtsCAGroup
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="AddMoverToGroup" Id="{ad749349-67a3-4a7b-bbde-0550486d46b8}">
      <Declaration><![CDATA[METHOD AddMoverToGroup : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="XtsCAGroup">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="XtsCAGroup.AddMoverToGroup">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>