<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Aborted" Id="{9d11f351-b4bf-4f98-a02b-044980c0fcf0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Aborted
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="CyclicLogic" Id="{f22e22e5-54e6-4715-a83e-723d936743bd}">
      <Declaration><![CDATA[METHOD CyclicLogic : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="Aborted">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Aborted.CyclicLogic">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>