<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Execute" Id="{16de238c-02d0-4654-b592-0c63039045d2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Execute
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="CyclicLogic" Id="{ac050c99-a704-455e-9c5a-e556222f067a}">
      <Declaration><![CDATA[METHOD CyclicLogic : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="Execute">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Execute.CyclicLogic">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>