<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Execute" Id="{16de238c-02d0-4654-b592-0c63039045d2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Execute IMPLEMENTS ITF_PackMLState, ITF_States
VAR
	_MyContext : ITF_PackMLMachine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="AbortingState" Id="{117e18fd-d58c-49a3-a3e7-076b0e1d6131}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY AbortingState : ITF_PackMLState
]]></Declaration>
      <Get Name="Get" Id="{0b12638e-f476-4af7-9ee9-ebc3a2cd1c1a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{5ca3f8d9-bf37-4023-95dc-c1fa0896548d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="CyclicLogic" Id="{ac050c99-a704-455e-9c5a-e556222f067a}">
      <Declaration><![CDATA[METHOD CyclicLogic : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="EStop" Id="{2ba6e0cd-1efe-4003-8123-65a9ba9b7ac2}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD EStop : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="MyNextState" Id="{bf5391d5-4695-4a63-9675-e3d0d28a01c4}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY MyNextState : ITF_PackMLState
]]></Declaration>
      <Get Name="Get" Id="{95972f3a-3769-430b-ac0f-81a8d916f4e3}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{a35f152d-4d91-48d7-9dc2-224f4e09e6de}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="Reset" Id="{1a9cf0ec-8b14-4e8d-9539-992a9b7b2e78}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Reset : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetContext" Id="{1700c1be-96df-4ce8-8a27-f90db3bd76f2}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD SetContext : BOOL
VAR_INPUT
	context	: ITF_PackMLMachine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_MyContext := context;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Start" Id="{42576e4a-c1d8-4012-9b36-1be3c4c250b5}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Start : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stop" Id="{26dae254-0c3f-4d8e-8ed6-04c9be98f59b}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Stop : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="StoppingState" Id="{f8561b74-af64-4c50-a52d-a1aad96e95b0}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY StoppingState : ITF_PackMLState
]]></Declaration>
      <Get Name="Get" Id="{ac7f6e50-1e86-4e13-8911-e68d13dedede}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{d56f0349-4bce-4904-97b6-f7cbb4713788}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <LineIds Name="Execute">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Execute.AbortingState.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Execute.AbortingState.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Execute.CyclicLogic">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="Execute.EStop">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Execute.MyNextState.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Execute.MyNextState.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Execute.Reset">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Execute.SetContext">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="Execute.Start">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Execute.Stop">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="Execute.StoppingState.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="Execute.StoppingState.Set">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>