<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Stopped" Id="{dc82a4e7-f66d-44be-8922-178610a55f51}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Stopped
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="CyclicLogic" Id="{e75c9e8e-13d6-4788-9283-68c0b718b073}">
      <Declaration><![CDATA[METHOD CyclicLogic : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="Stopped">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="Stopped.CyclicLogic">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>